/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardPosRouteImport } from './routes/dashboard/pos'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardLoginRouteImport } from './routes/dashboard/login'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard/inventory'
import { Route as DashboardIncomingStockRouteImport } from './routes/dashboard/incoming-stock'
import { Route as DashboardExpensesRouteImport } from './routes/dashboard/expenses'
import { Route as DashboardEmailsRouteImport } from './routes/dashboard/emails'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardOrdersRefRouteImport } from './routes/dashboard/orders.$ref'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPosRoute = DashboardPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIncomingStockRoute = DashboardIncomingStockRouteImport.update({
  id: '/incoming-stock',
  path: '/incoming-stock',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpensesRoute = DashboardExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailsRoute = DashboardEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRefRoute = DashboardOrdersRefRouteImport.update({
  id: '/$ref',
  path: '/$ref',
  getParentRoute: () => DashboardOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/emails': typeof DashboardEmailsRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/incoming-stock': typeof DashboardIncomingStockRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/orders/$ref': typeof DashboardOrdersRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/emails': typeof DashboardEmailsRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/incoming-stock': typeof DashboardIncomingStockRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/orders/$ref': typeof DashboardOrdersRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/emails': typeof DashboardEmailsRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/incoming-stock': typeof DashboardIncomingStockRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/orders/$ref': typeof DashboardOrdersRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/customers'
    | '/dashboard/emails'
    | '/dashboard/expenses'
    | '/dashboard/incoming-stock'
    | '/dashboard/inventory'
    | '/dashboard/login'
    | '/dashboard/orders'
    | '/dashboard/pos'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/orders/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/customers'
    | '/dashboard/emails'
    | '/dashboard/expenses'
    | '/dashboard/incoming-stock'
    | '/dashboard/inventory'
    | '/dashboard/login'
    | '/dashboard/orders'
    | '/dashboard/pos'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/orders/$ref'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/customers'
    | '/dashboard/emails'
    | '/dashboard/expenses'
    | '/dashboard/incoming-stock'
    | '/dashboard/inventory'
    | '/dashboard/login'
    | '/dashboard/orders'
    | '/dashboard/pos'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/orders/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pos': {
      id: '/dashboard/pos'
      path: '/pos'
      fullPath: '/dashboard/pos'
      preLoaderRoute: typeof DashboardPosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/incoming-stock': {
      id: '/dashboard/incoming-stock'
      path: '/incoming-stock'
      fullPath: '/dashboard/incoming-stock'
      preLoaderRoute: typeof DashboardIncomingStockRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/expenses': {
      id: '/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/emails': {
      id: '/dashboard/emails'
      path: '/emails'
      fullPath: '/dashboard/emails'
      preLoaderRoute: typeof DashboardEmailsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders/$ref': {
      id: '/dashboard/orders/$ref'
      path: '/$ref'
      fullPath: '/dashboard/orders/$ref'
      preLoaderRoute: typeof DashboardOrdersRefRouteImport
      parentRoute: typeof DashboardOrdersRoute
    }
  }
}

interface DashboardOrdersRouteChildren {
  DashboardOrdersRefRoute: typeof DashboardOrdersRefRoute
}

const DashboardOrdersRouteChildren: DashboardOrdersRouteChildren = {
  DashboardOrdersRefRoute: DashboardOrdersRefRoute,
}

const DashboardOrdersRouteWithChildren = DashboardOrdersRoute._addFileChildren(
  DashboardOrdersRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardEmailsRoute: typeof DashboardEmailsRoute
  DashboardExpensesRoute: typeof DashboardExpensesRoute
  DashboardIncomingStockRoute: typeof DashboardIncomingStockRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardOrdersRoute: typeof DashboardOrdersRouteWithChildren
  DashboardPosRoute: typeof DashboardPosRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardEmailsRoute: DashboardEmailsRoute,
  DashboardExpensesRoute: DashboardExpensesRoute,
  DashboardIncomingStockRoute: DashboardIncomingStockRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardOrdersRoute: DashboardOrdersRouteWithChildren,
  DashboardPosRoute: DashboardPosRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
